application: pythonjobsph 
version: 2 
runtime: python
api_version: 1

#builtins:
#- remote_api: on
#- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /admin/.*
  script: djangoappengine/main/main.py
  secure: always

- url: /.*
  script: djangoappengine/main/main.py

